name: timboo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler:
  shared_preferences:
  dio:
  file_picker:
  path_provider:
  device_info_plus:
  path_provider_ex2:
  video_player:
  chewie:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/header.png
   - assets/home.jpg
   - assets/initial.jpg

  fonts:
    - family: VAGRoundedStd
      fonts:
        - asset: assets/fonts/VAGRoundedStd-Black-TR-2.ttf
        - asset: assets/fonts/VAGRoundedStd-Bold-TR.ttf
        - asset: assets/fonts/VAGRoundedStd-Light-TR-3.ttf
        - asset: assets/fonts/VAGRoundedStd-Thin-TR.ttf